services:
  backend:
    build: ./
    command: "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - connection

  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - connection

networks:
  connection:

volumes:
  mysql_data:
